version: "3.9"
services:
  nginx: 
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis
      - REDIS_PORT=6379
      - SESSION_SECRET=random_secret
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mypassword123
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis


volumes:
  mongo-db:
